generate-pages:
  image: ruby:2.7
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public

deploy:
  needs:
    - job: generate-pages
      artifacts: true
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - # requires a ci/cd variable called SSH_PRIVATE_KEY set up, protected but not expanded/masked.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no -r public user@host.edu:/home/username
    - ssh -o StrictHostKeyChecking=no user@host.edu "cd /home/username; cp -r public /path/to/final/dest"
  only:
    - gh-pages


